Homework/config/routes.rb
Rails.application.routes.draw do
  resources :appointments

  resources :insurances

  resources :patients

  resources :specialists

end

Homework/app/models/specialist.rb
class Specialist < ActiveRecord::Base
  has_many :appointments
  has_many :patients, through: :appointments
end

Homework/app/controllers/specialists_controller.rb
class SpecialistsController < ApplicationController
  before_action :set_specialist, only: [:show, :edit, :update, :destroy]

  # GET /specialists
  # GET /specialists.json
  def index
    @specialists = Specialist.all
  end

  # GET /specialists/1
  # GET /specialists/1.json
  def show
  end

  # GET /specialists/new
  def new
    @specialist = Specialist.new
  end

  # GET /specialists/1/edit
  def edit
  end

  # POST /specialists
  # POST /specialists.json
  def create
    @specialist = Specialist.new(specialist_params)

    respond_to do |format|
      if @specialist.save
        format.html { redirect_to @specialist, notice: 'Specialist was successfully created.' }
        format.json { render :show, status: :created, location: @specialist }
      else
        format.html { render :new }
        format.json { render json: @specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialists/1
  # PATCH/PUT /specialists/1.json
  def update
    respond_to do |format|
      if @specialist.update(specialist_params)
        format.html { redirect_to @specialist, notice: 'Specialist was successfully updated.' }
        format.json { render :show, status: :ok, location: @specialist }
      else
        format.html { render :edit }
        format.json { render json: @specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialists/1
  # DELETE /specialists/1.json
  def destroy
    @specialist.destroy
    respond_to do |format|
      format.html { redirect_to specialists_url, notice: 'Specialist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialist
      @specialist = Specialist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specialist_params
      params.require(:specialist).permit(:name, :specialty)
    end
end

Homework/app/helpers/specialists_helper.rb
module SpecialistsHelper
end

Homework/app/views/specialists/_form.html.erb
<%= form_for(@specialist) do |f| %>
  <% if @specialist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@specialist.errors.count, "error") %> prohibited this specialist from being saved:</h2>

      <ul>
      <% @specialist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :specialty %><br>
    <%= f.text_field :specialty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Homework/app/views/specialists/edit.html.erb
<h1>Editing specialist</h1>

<%= render 'form' %>

<%= link_to 'Show', @specialist %> |
<%= link_to 'Back', specialists_path %>

Homework/app/views/specialists/index.html.erb
<h1>Listing specialists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Specialty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specialists.each do |specialist| %>
      <tr>
        <td><%= specialist.name %></td>
        <td><%= specialist.specialty %></td>
        <td><%= link_to 'Show', specialist %></td>
        <td><%= link_to 'Edit', edit_specialist_path(specialist) %></td>
        <td><%= link_to 'Destroy', specialist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Specialist', new_specialist_path %>

Homework/app/views/specialists/new.html.erb
<h1>New specialist</h1>

<%= render 'form' %>

<%= link_to 'Back', specialists_path %>

Homework/app/views/specialists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @specialist.name %>
</p>

<p>
  <strong>Specialty:</strong>
  <%= @specialist.specialty %>
</p>

<p>
  <strong>Patient Name:</strong>
  <% @specialist.patients.each do |patient|%>
      <%= patient.name %><br/>
      <% @specialist.appointments.each do |app| %>
          <%= app.appointment_date%>
          <strong>Next Appointment In ... Days</strong>
          <% a1 = app.appointment_date.yday %>
          <% a2 = Time.new.yday %>
          <%= a1-a2 %><br/>
      <%end%>
  <%end%>
</p>

<%= link_to 'Edit', edit_specialist_path(@specialist) %> |
<%= link_to 'Back', specialists_path %>