Homework/config/routes.rb
Rails.application.routes.draw do
  resources :appointments

  resources :insurances

  resources :patients

  resources :specialists

end

Homework/app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  belongs_to :specialist
  validates_presence_of :fee
end

Homework/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:specialist_id, :patient_id, :complaint, :appointment_date, :fee)
    end
end

Homework/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

Homework/app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :specialist_id %><br>
    <%= f.collection_select :specialist_id,Specialist.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.collection_select :patient_id,Patient.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :complaint %><br>
    <%= f.text_area :complaint %>
  </div>
  <div class="field">
    <%= f.label :appointment_date %><br>
    <%= f.date_select :appointment_date %>
  </div>

  <div class="field">
    <%= f.label :fee %><br>
    <%= f.text_area :fee %>
  </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

Homework/app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

Homework/app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Specialist</th>
      <th>Patient</th>
      <th>Complaint</th>
      <th>Appointment date</th>
      <th>Fee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.specialist.name %></td>
        <td><%= appointment.patient.name %></td>
        <td><%= appointment.complaint %></td>
        <td><%= appointment.appointment_date %></td>
        <td><%= appointment.fee %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

Homework/app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

Homework/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Specialist:</strong>
  <%= @appointment.specialist.name %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient.name %>
</p>

<p>
  <strong>Complaint:</strong>
  <%= @appointment.complaint %>
</p>

<p>
  <strong>Appointment date:</strong>
  <%= @appointment.appointment_date %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @appointment.fee %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>