Homework/config/routes.rb
Rails.application.routes.draw do
  resources :appointments

  resources :insurances

  resources :patients

  resources :specialists

end

Homework/app/models/insurance.rb
class Insurance < ActiveRecord::Base
  has_many :patients
end

Homework/app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  before_action :set_insurance, only: [:show, :edit, :update, :destroy]

  # GET /insurances
  # GET /insurances.json
  def index
    @insurances = Insurance.all
  end

  # GET /insurances/1
  # GET /insurances/1.json
  def show
  end

  # GET /insurances/new
  def new
    @insurance = Insurance.new
  end

  # GET /insurances/1/edit
  def edit
  end

  # POST /insurances
  # POST /insurances.json
  def create
    @insurance = Insurance.new(insurance_params)

    respond_to do |format|
      if @insurance.save
        format.html { redirect_to @insurance, notice: 'Insurance was successfully created.' }
        format.json { render :show, status: :created, location: @insurance }
      else
        format.html { render :new }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insurances/1
  # PATCH/PUT /insurances/1.json
  def update
    respond_to do |format|
      if @insurance.update(insurance_params)
        format.html { redirect_to @insurance, notice: 'Insurance was successfully updated.' }
        format.json { render :show, status: :ok, location: @insurance }
      else
        format.html { render :edit }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurances/1
  # DELETE /insurances/1.json
  def destroy
    @insurance.destroy
    respond_to do |format|
      format.html { redirect_to insurances_url, notice: 'Insurance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insurance
      @insurance = Insurance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insurance_params
      params.require(:insurance).permit(:name, :street_address)
    end
end

Homework/app/helpers/insurances_helper.rb
module InsurancesHelper
end

Homework/app/views/insurances/_form.html.erb
<%= form_for(@insurance) do |f| %>
  <% if @insurance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@insurance.errors.count, "error") %> prohibited this insurance from being saved:</h2>

      <ul>
      <% @insurance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br>
    <%= f.text_field :street_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Homework/app/views/insurances/edit.html.erb
<h1>Editing insurance</h1>

<%= render 'form' %>

<%= link_to 'Show', @insurance %> |
<%= link_to 'Back', insurances_path %>

Homework/app/views/insurances/index.html.erb
<h1>Listing insurances</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insurances.each do |insurance| %>
      <tr>
        <td><%= insurance.name %></td>
        <td><%= insurance.street_address %></td>
        <td><%= link_to 'Show', insurance %></td>
        <td><%= link_to 'Edit', edit_insurance_path(insurance) %></td>
        <td><%= link_to 'Destroy', insurance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insurance', new_insurance_path %>

Homework/app/views/insurances/new.html.erb
<h1>New insurance</h1>

<%= render 'form' %>

<%= link_to 'Back', insurances_path %>

Homework/app/views/insurances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @insurance.name %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @insurance.street_address %>
</p>

<%= link_to 'Edit', edit_insurance_path(@insurance) %> |
<%= link_to 'Back', insurances_path %>